apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue

  template:
    metadata:
      labels:
        app: demo
        version: blue

    spec:
      containers:
      - name: nginx
        image: 467685081921.dkr.ecr.us-east-1.amazonaws.com/bluegreen-demo:3c99547608b6da1c0b763c183d4e721eb30c51fa

        ports:
        - containerPort: 80
        