apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue

  template:
    metadata:
      labels:
        app: demo
        version: blue

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        - |
          echo "<h1 style='color:blue'>BLUE VERSION</h1>" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'
