apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo
      version: green

  template:
    metadata:
      labels:
        app: demo
        version: green

    spec:
      containers:
      - name: nginx
        image: 467685081921.dkr.ecr.us-east-1.amazonaws.com/bluegreen-demo:4803a1c98bc36342b71c530317ffced194b09b62

        ports:
        - containerPort: 80

      