apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue

  template:
    metadata:
      labels:
        app: demo
        version: blue

    spec:
      containers:
      - name: nginx
        image: 467685081921.dkr.ecr.us-east-1.amazonaws.com/bluegreen-demo:518788641fbb1d45c873057442890de63597f408

        ports:
        - containerPort: 80
        